/**
 * 200+ Curated Resources for Autistic Kids and Parents
 * Categories: Books, Articles, News, Research Papers, Organizations
 */

export const STATIC_RESOURCES = [
  // ============ BOOKS (30) ============
  { title: 'The Reason I Jump by Naoki Higashida', content: 'Written by a 13-year-old autistic boy; unique insights into the autistic mind.', link: 'https://www.penguinrandomhouse.com/books/300634/the-reason-i-jump-by-naoki-higashida/', category: 'EDUCATION' },
  { title: 'NeuroTribes by Steve Silberman', content: 'Award-winning history of autism and the neurodiversity movement.', link: 'https://www.penguinrandomhouse.com/books/314283/neurotribes-by-steve-silberman/', category: 'EDUCATION' },
  { title: 'Uniquely Human by Barry M. Prizant', content: 'Understanding autistic behaviors as coping mechanisms, not problems to fix.', link: 'https://www.uniquelyhuman.com/', category: 'BEHAVIOR' },
  { title: 'The Whole-Brain Child by Daniel J. Siegel', content: 'Brain-based strategies for nurturing your child\'s developing mind.', link: 'https://www.drdansiegel.com/books/the_whole_brain_child/', category: 'EDUCATION' },
  { title: 'Ten Things Every Child with Autism Wishes You Knew', content: 'Essential insights from Ellen Notbohm for parents and educators.', link: 'https://www.futurehorizons.com/products/ten-things-every-child-with-autism-wishes-you-knew', category: 'EDUCATION' },
  { title: 'Thinking in Pictures by Temple Grandin', content: 'Temple Grandin shares her visual thinking and autism experience.', link: 'https://www.templegrandin.com/books.html', category: 'EDUCATION' },
  { title: 'Look Me in the Eye by John Elder Robison', content: 'NYT bestseller memoir about life with Asperger\'s.', link: 'https://johnrobison.com/books/', category: 'EDUCATION' },
  { title: 'The Explosive Child by Ross Greene', content: 'Collaborative problem-solving for inflexible, explosive kids.', link: 'https://www.livesinthebalance.org/explosive-child', category: 'BEHAVIOR' },
  { title: 'An Early Start for Your Child with Autism', content: 'Evidence-based strategies for toddlers and preschoolers.', link: 'https://www.guilford.com/books/An-Early-Start-for-Your-Child-with-Autism/Rogers-Dawson-Vismara/9781462503896', category: 'EDUCATION' },
  { title: 'Sensory Processing 101', content: 'Understanding sensory challenges and practical strategies.', link: 'https://www.sensoryprocessing101.com/', category: 'BEHAVIOR' },
  { title: 'The Out-of-Sync Child by Carol Kranowitz', content: 'Recognizing and coping with sensory processing disorder.', link: 'https://www.out-of-sync-child.com/', category: 'BEHAVIOR' },
  { title: 'Raising a Sensory Smart Child', content: 'Definitive handbook for parents of sensory-sensitive kids.', link: 'https://www.sensorysmarts.com/', category: 'BEHAVIOR' },
  { title: 'The Social Skills Picture Book', content: 'Teaching play, emotion, and communication through photographs.', link: 'https://www.futurehorizons.com/products/the-social-skills-picture-book', category: 'SOCIAL_SKILLS' },
  { title: 'No-Drama Discipline by Daniel Siegel', content: 'Whole-brain way to calm chaos and nurture development.', link: 'https://www.drdansiegel.com/books/no_drama_discipline/', category: 'BEHAVIOR' },
  { title: 'The Verbal Behavior Approach', content: 'How to teach children with autism and related disorders.', link: 'https://www.amazon.com/Verbal-Behavior-Approach-Children-Disorders/dp/1843108526', category: 'THERAPY' },
  { title: 'More Than Words by Fern Sussman', content: 'Hanen guide for parents of children with autism.', link: 'https://www.hanen.org/Guide/More-Than-Words.aspx', category: 'THERAPY' },
  { title: 'It Takes Two to Talk', content: 'Hanen program for parents of children with language delays.', link: 'https://www.hanen.org/Programs/For-Parents/It-Takes-Two-to-Talk.aspx', category: 'THERAPY' },
  { title: 'A Parent\'s Guide to High-Functioning Autism', content: 'Practical advice for daily life and challenges.', link: 'https://www.guilford.com/books/A-Parents-Guide-to-High-Functioning-Autism-Spectrum-Disorder/Ozonoff-Dawson-McPartland/9781462517473', category: 'EDUCATION' },
  { title: 'The Complete Guide to Asperger\'s Syndrome', content: 'Comprehensive reference by Tony Attwood.', link: 'https://www.jkp.com/uk/the-complete-guide-to-aspergers-syndrome.html', category: 'EDUCATION' },
  { title: 'Different Not Less by Temple Grandin', content: 'Inspiring stories of autistic individuals who succeeded.', link: 'https://www.amazon.com/Different-Not-Less-Inspiring-Disorder/dp/1941765040', category: 'COMMUNITY' },
  { title: 'Louder Than Words by Jenny McCarthy', content: 'A mother\'s journey with autism and recovery approaches.', link: 'https://www.penguinrandomhouse.com/books/299880/louder-than-words-by-jenny-mccarthy/', category: 'COMMUNITY' },
  { title: 'The Autism Mom\'s Survival Guide', content: 'Practical support and self-care for autism parents.', link: 'https://www.susansenator.com/books', category: 'COMMUNITY' },
  { title: '101 Games and Activities for Children With Autism', content: 'Sensory integration and fun learning activities.', link: 'https://www.amazon.com/101-Games-Activities-Children-Autism/dp/1935274937', category: 'EDUCATION' },
  { title: 'Social Stories for Kids with Autism', content: 'Carol Gray\'s Social Stories methodology and examples.', link: 'https://carolgraysocialstories.com/', category: 'SOCIAL_SKILLS' },
  { title: 'The Loving Push by Temple Grandin', content: 'How parents and professionals can help autistic kids succeed.', link: 'https://www.futurehorizons.com/products/the-loving-push', category: 'EDUCATION' },
  { title: 'Uniquely Wired by Julia Cook', content: 'Children\'s book celebrating autism differences.', link: 'https://www.juliacookonline.com/books/uniquely-wired', category: 'EDUCATION' },
  { title: 'All My Stripes by Shaina Rudolph', content: 'Picture book for kids about autism and acceptance.', link: 'https://www.maginationpress.com/books/all-my-stripes/', category: 'EDUCATION' },
  { title: 'Ian\'s Walk by Laurie Lears', content: 'Story about a sister and her autistic brother.', link: 'https://www.amazon.com/Ians-Walk-Learning-Autism-Laurie/dp/0807524450', category: 'EDUCATION' },
  { title: 'The Survival Guide for Kids with Autism Spectrum Disorders', content: 'Age-appropriate strategies for autistic children.', link: 'https://www.freespirit.com/special-needs-autism/survival-guide-kids-autism-spectrum', category: 'EDUCATION' },
  { title: 'Carly\'s Voice by Arthur Fleischmann', content: 'Breakthrough memoir of nonverbal autistic girl who found her voice.', link: 'https://carlysvoice.com/', category: 'EDUCATION' },

  // ============ RESEARCH & ARTICLES (50) ============
  { title: 'NIH Autism Spectrum Disorder Research', content: 'National Institutes of Health research on autism causes and treatments.', link: 'https://www.nimh.nih.gov/health/topics/autism-spectrum-disorders-asd', category: 'EDUCATION' },
  { title: 'CDC Autism Data and Statistics', content: 'Prevalence, screening, and surveillance data from CDC.', link: 'https://www.cdc.gov/ncbddd/autism/data.html', category: 'EDUCATION' },
  { title: 'Autism Research Institute Studies', content: 'Research on biomedical and educational interventions.', link: 'https://www.autism.org/research/', category: 'EDUCATION' },
  { title: 'PubMed Autism Research', content: 'Peer-reviewed research papers on autism spectrum disorders.', link: 'https://pubmed.ncbi.nlm.nih.gov/?term=autism+spectrum+disorder', category: 'EDUCATION' },
  { title: 'Journal of Autism and Developmental Disorders', content: 'Leading peer-reviewed journal on autism research.', link: 'https://link.springer.com/journal/10803', category: 'EDUCATION' },
  { title: 'Autism Evidence-Based Practices', content: 'NPDC and NCAEP evidence-based practice reports.', link: 'https://autismpdc.fpg.unc.edu/evidence-based-practices', category: 'EDUCATION' },
  { title: 'ABA Evidence Base - APBA', content: 'Association of Professional Behavior Analysts on ABA research.', link: 'https://www.apbahome.net/', category: 'THERAPY' },
  { title: 'Speech-Language Development in Autism', content: 'ASHA research on communication and autism.', link: 'https://www.asha.org/practice-portal/clinical-topics/autism/', category: 'THERAPY' },
  { title: 'Sensory Integration Research', content: 'STAR Institute and SPD Foundation research.', link: 'https://www.spdstar.org/basic/research', category: 'BEHAVIOR' },
  { title: 'Sleep and Autism Research', content: 'Studies on sleep disturbances in autistic children.', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7346127/', category: 'SLEEP' },
  { title: 'Feeding and Nutrition in Autism', content: 'Research on feeding difficulties and nutritional interventions.', link: 'https://www.autismspeaks.org/expert-opinion/feeding-issues-and-children-autism', category: 'NUTRITION' },
  { title: 'Early Intervention Outcomes', content: 'Research on effectiveness of early autism intervention.', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4918724/', category: 'THERAPY' },
  { title: 'IEP and Special Education Research', content: 'Evidence-based practices in special education.', link: 'https://ies.ed.gov/ncee/wwc/', category: 'LEGAL' },
  { title: 'Parent-Mediated Interventions', content: 'Research on parent training for autism support.', link: 'https://www.cochrane.org/CD009774/BEHAV_parent-mediated-interventions', category: 'THERAPY' },
  { title: 'Social Skills Intervention Research', content: 'Evidence for social skills training programs.', link: 'https://pubmed.ncbi.nlm.nih.gov/23633377/', category: 'SOCIAL_SKILLS' },
  { title: 'Anxiety and Autism', content: 'Comorbidity of anxiety in autistic individuals.', link: 'https://www.autism.org/anxiety/', category: 'BEHAVIOR' },
  { title: 'ADHD and Autism Overlap', content: 'Understanding co-occurring ADHD and autism.', link: 'https://www.additudemag.com/autism-adhd-overlap-symptoms/', category: 'EDUCATION' },
  { title: 'Gender and Autism', content: 'Research on autism presentation in girls and women.', link: 'https://www.autism.org/autism-in-girls-and-women/', category: 'EDUCATION' },
  { title: 'Executive Function in Autism', content: 'Understanding planning, flexibility, and organization.', link: 'https://www.understood.org/en/articles/executive-function-issues-and-autism', category: 'EDUCATION' },
  { title: 'Autism and Employment', content: 'Research on employment outcomes for autistic adults.', link: 'https://www.autism-society.org/living-with-autism/employment/', category: 'COMMUNITY' },
  { title: 'Genetic Research in Autism', content: 'Advances in understanding autism genetics.', link: 'https://www.autismspeaks.org/science-news', category: 'EDUCATION' },
  { title: 'Meltdowns vs Tantrums', content: 'Understanding the difference and de-escalation strategies.', link: 'https://www.autism.org.uk/advice-and-guidance/topics/behaviour/meltdowns', category: 'BEHAVIOR' },
  { title: 'Visual Supports Evidence', content: 'AFIRM module on visual supports and schedules.', link: 'https://afirm.fpg.unc.edu/visual-supports', category: 'BEHAVIOR' },
  { title: 'Stimming and Self-Regulation', content: 'Understanding repetitive behaviors in autism.', link: 'https://www.autism.org/stimming/', category: 'BEHAVIOR' },
  { title: 'Bullying and Autism', content: 'Research on bullying prevalence and prevention.', link: 'https://www.stopbullying.gov/bullying/special-needs', category: 'SOCIAL_SKILLS' },
  { title: 'Transition to Adulthood Research', content: 'Outcomes and support for autistic youth.', link: 'https://www.autismspeaks.org/tool-kit/transition-tool-kit', category: 'EDUCATION' },
  { title: 'Medication and Autism', content: 'Evidence on medication for co-occurring conditions.', link: 'https://www.autism.org/medication-for-autism/', category: 'EDUCATION' },
  { title: 'Teletherapy for Autism', content: 'Research on virtual therapy effectiveness.', link: 'https://www.asha.org/practice-portal/clinical-topics/telepractice/', category: 'THERAPY' },
  { title: 'Screen Time and Autism', content: 'Balancing technology use for autistic children.', link: 'https://www.autismspeaks.org/expert-opinion/screen-time-and-autism', category: 'EDUCATION' },
  { title: 'Cultural Considerations in Autism', content: 'Autism support across cultures and languages.', link: 'https://www.autism.org/autism-in-diverse-communities/', category: 'COMMUNITY' },
  { title: 'Sibling Support Research', content: 'Supporting siblings of autistic children.', link: 'https://www.siblingsupport.org/', category: 'COMMUNITY' },
  { title: 'Grandparent Support', content: 'Resources for grandparents of autistic children.', link: 'https://www.autism-society.org/living-with-autism/family/grandparents/', category: 'COMMUNITY' },
  { title: 'Mental Health in Autism', content: 'Depression, anxiety, and mental health support.', link: 'https://www.autism.org/mental-health/', category: 'BEHAVIOR' },
  { title: 'Sensory Overload', content: 'Understanding and managing sensory overwhelm.', link: 'https://www.healthline.com/health/autism/sensory-overload', category: 'BEHAVIOR' },
  { title: 'Autism and Puberty', content: 'Guidance for parents on puberty and autism.', link: 'https://www.autism.org/puberty-and-autism/', category: 'EDUCATION' },
  { title: 'Dental Care and Autism', content: 'Strategies for dental visits and oral care.', link: 'https://www.autismspeaks.org/expert-opinion/dental-care-and-autism', category: 'OTHER' },
  { title: 'Haircuts and Autism', content: 'Tips for haircuts and grooming.', link: 'https://www.autism.org/haircuts-and-autism/', category: 'OTHER' },
  { title: 'Toilet Training and Autism', content: 'Evidence-based toilet training strategies.', link: 'https://www.autismspeaks.org/tool-kit/atnair-p-toilet-training-tool-kit', category: 'BEHAVIOR' },
  { title: 'Wandering and Elopement', content: 'Safety resources for wandering prevention.', link: 'https://nationalautismassociation.org/resources/autism-safety-facts/', category: 'COMMUNITY' },
  { title: 'Autism and Epilepsy', content: 'Understanding seizure disorders in autism.', link: 'https://www.autism.org/epilepsy-and-autism/', category: 'EDUCATION' },
  { title: 'GI Issues and Autism', content: 'Research on gastrointestinal problems.', link: 'https://www.autism.org/gastrointestinal-problems/', category: 'NUTRITION' },
  { title: 'Picky Eating Research', content: 'Strategies for selective eating in autism.', link: 'https://www.eatright.org/food/nutrition/eating-as-a-family/picky-eaters', category: 'NUTRITION' },
  { title: 'ARFID and Autism', content: 'Avoidant/restrictive food intake disorder.', link: 'https://www.nationaleatingdisorders.org/learn/by-eating-disorder/arfid', category: 'NUTRITION' },
  { title: 'Melatonin and Sleep', content: 'Research on melatonin for sleep in autism.', link: 'https://www.sleepfoundation.org/sleep-aids/melatonin', category: 'SLEEP' },
  { title: 'Sleep Hygiene Guide', content: 'Tips for better sleep in autistic children.', link: 'https://www.sleepfoundation.org/children-and-sleep/autism-and-sleep', category: 'SLEEP' },
  { title: 'Insurance Mandates by State', content: 'Autism insurance coverage requirements.', link: 'https://www.autism-society.org/living-with-autism/autism-through-the-lifespan/autism-insurance/', category: 'FINANCIAL' },
  { title: 'SSI for Children with Disabilities', content: 'Supplemental Security Income eligibility.', link: 'https://www.ssa.gov/benefits/disability/apply-child.html', category: 'FINANCIAL' },
  { title: 'ABLE Accounts', content: 'Tax-advantaged savings for disability.', link: 'https://www.ablenrc.org/', category: 'FINANCIAL' },
  { title: 'Special Needs Trusts', content: 'Protecting assets for children with disabilities.', link: 'https://www.specialneedsalliance.org/', category: 'FINANCIAL' },
  { title: 'Autism Grants and Funding', content: 'Financial assistance programs.', link: 'https://www.autismspeaks.org/autism-grants', category: 'FINANCIAL' },
  { title: 'Tax Benefits for Autism', content: 'Dependent care and medical expense deductions.', link: 'https://www.irs.gov/credits-deductions/individuals/earned-income-tax-credit', category: 'FINANCIAL' },
  { title: 'Wrightslaw Special Education Law', content: 'IEP, IDEA, and advocacy resources.', link: 'https://www.wrightslaw.com', category: 'LEGAL' },
  { title: 'COPAA - Special Education Advocates', content: 'Council of Parent Attorneys and Advocates.', link: 'https://www.copaa.org', category: 'LEGAL' },
  { title: 'DREDF Disability Rights', content: 'Disability Rights Education and Defense Fund.', link: 'https://dredf.org/', category: 'LEGAL' },
  { title: 'PACER Center', content: 'Parent training and disability advocacy.', link: 'https://www.pacer.org', category: 'LEGAL' },
  { title: 'IEP Goal Bank', content: 'Measurable IEP goals by skill area.', link: 'https://www.weareteachers.com/iep-goal-bank/', category: 'LEGAL' },
  { title: 'Due Process and Complaints', content: 'Filing complaints and due process in special ed.', link: 'https://www.wrightslaw.com/info/due.process.index.htm', category: 'LEGAL' },

  // ============ NEWS & CURRENT AFFAIRS (20) ============
  { title: 'Autism Society News', content: 'Latest news and updates from Autism Society.', link: 'https://autismsociety.org/news/', category: 'COMMUNITY' },
  { title: 'Autism Speaks Blog', content: 'News, stories, and expert advice.', link: 'https://www.autismspeaks.org/blog', category: 'COMMUNITY' },
  { title: 'Spectrum News', content: 'In-depth journalism on autism research.', link: 'https://www.spectrumnews.org/', category: 'EDUCATION' },
  { title: 'Thinking Person\'s Guide to Autism', content: 'Blog and news from autistic voices and parents.', link: 'https://thinkingpersonsguidetoautism.com/', category: 'COMMUNITY' },
  { title: 'Autistic Self Advocacy Network News', content: 'Policy updates and neurodiversity advocacy.', link: 'https://autisticadvocacy.org/about-asan/asan-news/', category: 'COMMUNITY' },
  { title: 'CDC Autism Updates', content: 'Latest CDC data and guidelines.', link: 'https://www.cdc.gov/ncbddd/autism/index.html', category: 'EDUCATION' },
  { title: 'AAP Autism Resources', content: 'American Academy of Pediatrics autism guidelines.', link: 'https://www.aap.org/en/patient-care/autism/', category: 'EDUCATION' },
  { title: 'WHO Autism Information', content: 'World Health Organization autism facts.', link: 'https://www.who.int/news-room/fact-sheets/detail/autism-spectrum-disorders', category: 'EDUCATION' },
  { title: 'NIH News on Autism', content: 'National Institutes of Health autism research news.', link: 'https://www.nimh.nih.gov/news/science-news', category: 'EDUCATION' },
  { title: 'Research Autism News', content: 'UK-based autism research updates.', link: 'https://researchautism.org/', category: 'EDUCATION' },
  { title: 'Autism Research News', content: 'Latest peer-reviewed research summaries.', link: 'https://www.spectrumnews.org/news/', category: 'EDUCATION' },
  { title: 'Neurodiversity in the Workplace', content: 'Trends in autism employment.', link: 'https://hbr.org/topic/subject/neurodiversity', category: 'COMMUNITY' },
  { title: 'Autism Parenting Magazine', content: 'Tips, stories, and resources for parents.', link: 'https://www.autismparentingmagazine.com/', category: 'COMMUNITY' },
  { title: 'Wrong Planet Community', content: 'Online community for autistic individuals.', link: 'https://wrongplanet.net/', category: 'COMMUNITY' },
  { title: 'Reddit r/autism', content: 'Community discussion and support.', link: 'https://www.reddit.com/r/autism/', category: 'COMMUNITY' },
  { title: 'NeuroClastic', content: 'Autistic-led blog and perspectives.', link: 'https://neuroclastic.com/', category: 'COMMUNITY' },
  { title: 'Autism Dad Blog', content: 'Parent perspective and daily life.', link: 'https://www.google.com/search?q=autism+dad+blog', category: 'COMMUNITY' },
  { title: 'The Mighty - Autism', content: 'Personal stories and community support.', link: 'https://themighty.com/topic/autism/', category: 'COMMUNITY' },
  { title: 'Autism Support Groups', content: 'Finding local and online support groups.', link: 'https://www.autism-society.org/get-involved/local-chapters/', category: 'COMMUNITY' },

  // ============ ORGANIZATIONS & ADVOCACY (40) ============
  { title: 'Autistic Self Advocacy Network (ASAN)', content: 'Run by and for autistic people; "Nothing About Us Without Us."', link: 'https://autisticadvocacy.org', category: 'COMMUNITY' },
  { title: 'Autism Society of America', content: 'Advocacy, support, and resources nationwide.', link: 'https://autismsociety.org/', category: 'COMMUNITY' },
  { title: 'National Autism Association', content: 'Safety, wandering prevention, family support.', link: 'https://nationalautismassociation.org', category: 'COMMUNITY' },
  { title: 'Autism Speaks', content: 'Research, advocacy, and resource toolkits.', link: 'https://www.autismspeaks.org', category: 'COMMUNITY' },
  { title: 'TACA - The Autism Community in Action', content: 'Education and support for families.', link: 'https://tacanow.org', category: 'COMMUNITY' },
  { title: 'Autism Research Institute', content: 'Research and educational resources.', link: 'https://www.autism.org/', category: 'EDUCATION' },
  { title: 'Organization for Autism Research (OAR)', content: 'Applied science for daily challenges.', link: 'https://researchautism.org/', category: 'EDUCATION' },
  { title: 'Sesame Street and Autism', content: 'Sesame Workshop resources for autism families.', link: 'https://autism.sesamestreet.org/', category: 'EDUCATION' },
  { title: 'Understood.org', content: 'Resources for learning and thinking differences.', link: 'https://www.understood.org', category: 'EDUCATION' },
  { title: 'Child Mind Institute', content: 'Mental health and learning disorder resources.', link: 'https://childmind.org/topics/autism-spectrum-disorder/', category: 'EDUCATION' },
  { title: 'Raising Children Network - Autism', content: 'Australian evidence-based parenting guide.', link: 'https://raisingchildren.net.au/autism', category: 'EDUCATION' },
  { title: 'Pathways.org', content: 'Developmental milestones and early detection.', link: 'https://pathways.org/', category: 'EDUCATION' },
  { title: 'Zero to Three', content: 'Early childhood development resources.', link: 'https://www.zerotothree.org/', category: 'EDUCATION' },
  { title: 'AFIRM Modules', content: 'Free online training on evidence-based practices.', link: 'https://afirm.fpg.unc.edu/', category: 'THERAPY' },
  { title: 'Hanen Centre', content: 'Speech and language programs for parents.', link: 'https://www.hanen.org/', category: 'THERAPY' },
  { title: 'TEACCH Autism Program', content: 'Structured teaching and visual supports.', link: 'https://teacch.com', category: 'THERAPY' },
  { title: 'Social Thinking', content: 'Social competency curriculum.', link: 'https://www.socialthinking.com', category: 'SOCIAL_SKILLS' },
  { title: 'Zones of Regulation', content: 'Self-regulation curriculum.', link: 'https://www.zonesofregulation.com', category: 'BEHAVIOR' },
  { title: 'STAR Institute', content: 'Sensory processing and occupational therapy.', link: 'https://www.spdstar.org', category: 'BEHAVIOR' },
  { title: 'SPD Foundation', content: 'Sensory processing disorder resources.', link: 'https://www.spdfoundation.net', category: 'BEHAVIOR' },
  { title: 'American Speech-Language-Hearing Association', content: 'ASHA resources for communication.', link: 'https://www.asha.org', category: 'THERAPY' },
  { title: 'American Occupational Therapy Association', content: 'AOTA resources for OT and autism.', link: 'https://www.aota.org', category: 'THERAPY' },
  { title: 'Behavior Analyst Certification Board', content: 'Finding certified ABA providers.', link: 'https://www.bacb.com/', category: 'THERAPY' },
  { title: 'Association for Science in Autism Treatment', content: 'Evidence-based treatment information.', link: 'https://asatonline.org/', category: 'THERAPY' },
  { title: 'SOS Approach to Feeding', content: 'Feeding therapy program for picky eaters.', link: 'https://sosapproachtofeeding.com', category: 'NUTRITION' },
  { title: 'Feeding Matters', content: 'Pediatric feeding disorder resources.', link: 'https://www.feedingmatters.org/', category: 'NUTRITION' },
  { title: 'Project Lifesaver', content: 'Tracking for individuals who wander.', link: 'https://projectlifesaver.org', category: 'COMMUNITY' },
  { title: 'Siblings Support', content: 'Support for siblings of disabled children.', link: 'https://www.siblingsupport.org/', category: 'COMMUNITY' },
  { title: 'Family Voices', content: 'Family-centered care for children with special needs.', link: 'https://familyvoices.org/', category: 'COMMUNITY' },
  { title: 'Parent to Parent USA', content: 'Peer support for parents of children with disabilities.', link: 'https://www.p2pusa.org/', category: 'COMMUNITY' },
  { title: 'Easterseals', content: 'Services for people with disabilities.', link: 'https://www.easterseals.com/', category: 'COMMUNITY' },
  { title: 'Arc of the United States', content: 'Advocacy for people with intellectual disabilities.', link: 'https://thearc.org/', category: 'COMMUNITY' },
  { title: 'Best Buddies', content: 'Friendship and employment for people with IDD.', link: 'https://www.bestbuddies.org/', category: 'COMMUNITY' },
  { title: 'Special Olympics', content: 'Sports and inclusion for people with disabilities.', link: 'https://www.specialolympics.org/', category: 'COMMUNITY' },
  { title: 'Job Accommodation Network', content: 'Workplace accommodations for autism.', link: 'https://askjan.org/disabilities/Autism-Spectrum-Disorder.cfm', category: 'COMMUNITY' },
  { title: 'Autism at Work Programs', content: 'Employer resources for hiring autistic individuals.', link: 'https://www.autismspeaks.org/autism-workplace', category: 'COMMUNITY' },

  // ============ APPS & TECHNOLOGY (20) ============
  { title: 'Proloquo2Go AAC', content: 'Award-winning augmentative communication app.', link: 'https://www.assistiveware.com/products/proloquo2go', category: 'THERAPY' },
  { title: 'TouchChat AAC', content: 'Full-featured AAC solution.', link: 'https://touchchatapp.com/', category: 'THERAPY' },
  { title: 'LAMP Words for Life', content: 'Language acquisition through motor planning.', link: 'https://www.aacandautism.com/lamp', category: 'THERAPY' },
  { title: 'GoTalk NOW', content: 'AAC app with customizable communication boards.', link: 'https://www.gotalknow.com/', category: 'THERAPY' },
  { title: 'Choiceworks', content: 'Visual schedule and choice board app.', link: 'https://www.beevisual.com/choiceworks', category: 'BEHAVIOR' },
  { title: 'First Then Visual Schedule', content: 'Simple visual schedule app.', link: 'https://www.goodkarmaapplications.com', category: 'BEHAVIOR' },
  { title: 'Otsimo', content: 'Educational games for autistic children.', link: 'https://otsimo.com/', category: 'EDUCATION' },
  { title: 'Zones of Regulation App', content: 'Self-regulation and emotion identification.', link: 'https://www.zonesofregulation.com/learn-more-about-the-zones-of-regulation-app.html', category: 'BEHAVIOR' },
  { title: 'Autism iHelp', content: 'Language and concept learning app.', link: 'https://www.autismihelp.com/', category: 'EDUCATION' },
  { title: 'Model Me Going Places', content: 'Video modeling for community skills.', link: 'https://modelmekids.com', category: 'SOCIAL_SKILLS' },
  { title: 'Sosh App', content: 'Social skills development for teens and adults.', link: 'https://www.sosh.com/', category: 'SOCIAL_SKILLS' },
  { title: 'Grace App', content: 'Picture-based communication for nonverbal users.', link: 'https://www.graceapp.com/', category: 'THERAPY' },
  { title: 'Pictello', content: 'Create talking photo albums and social stories.', link: 'https://www.assistiveware.com/products/pictello', category: 'SOCIAL_SKILLS' },
  { title: 'Choiceworks Calendar', content: 'Daily routine and calendar app.', link: 'https://www.beevisual.com/', category: 'BEHAVIOR' },
  { title: 'AngelSense', content: 'GPS tracking for autism safety.', link: 'https://www.angelsense.com/', category: 'COMMUNITY' },
  { title: 'Constant Therapy', content: 'Speech and cognitive therapy app.', link: 'https://constanttherapy.com/', category: 'THERAPY' },
  { title: 'Endless Reader', content: 'Sight words and reading for kids.', link: 'https://www.originatorkids.com/endless-reader', category: 'EDUCATION' },
  { title: 'Avaz App', content: 'AAC for children and adults.', link: 'https://www.avazapp.com/', category: 'THERAPY' },
  { title: 'Speech Blubs', content: 'Speech therapy and language development.', link: 'https://speechblubs.com/', category: 'THERAPY' },
  { title: 'Sensory App House', content: 'Calming and sensory apps for kids.', link: 'https://www.sensoryapphouse.com/', category: 'BEHAVIOR' },

  // ============ THERAPY & INTERVENTION (20) ============
  { title: 'ABA Therapy Overview', content: 'Applied Behavior Analysis explained.', link: 'https://www.autismspeaks.org/applied-behavior-analysis', category: 'THERAPY' },
  { title: 'Floortime/DIR Model', content: 'Developmental, individual-difference, relationship-based approach.', link: 'https://www.icdl.com/dir', category: 'THERAPY' },
  { title: 'Early Start Denver Model', content: 'Naturalistic developmental behavioral intervention.', link: 'https://health.ucdavis.edu/mindinstitute/our-team/faculty_staff/esdm.html', category: 'THERAPY' },
  { title: 'Pivotal Response Treatment', content: 'PRT naturalistic intervention approach.', link: 'https://www.autismprthelp.com/', category: 'THERAPY' },
  { title: 'SCERTS Model', content: 'Social communication, emotional regulation, transactional support.', link: 'https://scerts.com/', category: 'THERAPY' },
  { title: 'Speech Therapy for Autism', content: 'ASHA guide to speech-language therapy.', link: 'https://www.asha.org/public/speech/disorders/autism/', category: 'THERAPY' },
  { title: 'Occupational Therapy for Autism', content: 'Sensory integration and daily living skills.', link: 'https://www.aota.org/About-Occupational-Therapy/Patients-Clients/ChildrenAndYouth/Autism.aspx', category: 'THERAPY' },
  { title: 'Physical Therapy and Autism', content: 'Gross motor and coordination support.', link: 'https://www.apta.org/patient-care/conditions-and-disabilities/autism-spectrum-disorder', category: 'THERAPY' },
  { title: 'Music Therapy and Autism', content: 'Benefits of music therapy.', link: 'https://www.musictherapy.org/about/musictherapy/', category: 'THERAPY' },
  { title: 'Art Therapy for Autism', content: 'Creative expression and communication.', link: 'https://www.arttherapy.org/upload/2015_ATA_Position_Statement_on_Autism.pdf', category: 'THERAPY' },
  { title: 'Equine Therapy', content: 'Horse-assisted therapy for autism.', link: 'https://www.pathintl.org/', category: 'THERAPY' },
  { title: 'Play Therapy', content: 'Child-centered play therapy approaches.', link: 'https://www.a4pt.org/', category: 'THERAPY' },
  { title: 'Social Skills Groups', content: 'Finding and evaluating social skills programs.', link: 'https://www.socialthinking.com/', category: 'SOCIAL_SKILLS' },
  { title: 'PEERS Program', content: 'Evidence-based social skills intervention.', link: 'https://www.semel.ucla.edu/peers', category: 'SOCIAL_SKILLS' },
  { title: 'Social Stories Guide', content: 'Creating and using Social Stories.', link: 'https://carolgraysocialstories.com/social-stories/what-is-it/', category: 'SOCIAL_SKILLS' },
  { title: 'Video Modeling', content: 'Using video to teach skills.', link: 'https://afirm.fpg.unc.edu/video-modeling', category: 'THERAPY' },
  { title: 'Peer-Mediated Instruction', content: 'Using peers to teach social skills.', link: 'https://afirm.fpg.unc.edu/peer-mediated-instruction-intervention', category: 'SOCIAL_SKILLS' },
  { title: 'Naturalistic Teaching', content: 'Embedding teaching in natural routines.', link: 'https://afirm.fpg.unc.edu/naturalistic-intervention', category: 'THERAPY' },
  { title: 'Discrete Trial Training', content: 'Structured ABA teaching method.', link: 'https://afirm.fpg.unc.edu/discrete-trial-training', category: 'THERAPY' },
  { title: 'Picture Exchange Communication', content: 'PECS augmentative communication system.', link: 'https://pecsusa.com/pecs/', category: 'THERAPY' },

  // ============ DAILY LIFE & PRACTICAL (20) ============
  { title: 'Creating Routines', content: 'Importance of predictable routines for autistic children.', link: 'https://www.autism.org/the-importance-of-routines/', category: 'BEHAVIOR' },
  { title: 'Preparing for Doctor Visits', content: 'Social stories and strategies for medical appointments.', link: 'https://www.autismspeaks.org/tool-kit/atnair-p-visiting-doctor', category: 'OTHER' },
  { title: 'Flying with Autism', content: 'Tips for air travel with autistic children.', link: 'https://www.tsa.gov/travel/special-procedures', category: 'OTHER' },
  { title: 'Holiday Survival Guide', content: 'Managing holidays and family gatherings.', link: 'https://www.autism.org/holidays-and-autism/', category: 'BEHAVIOR' },
  { title: 'Back to School Tips', content: 'Transitioning to a new school year.', link: 'https://www.understood.org/en/articles/back-to-school-checklist-for-kids-with-autism', category: 'EDUCATION' },
  { title: 'Birthday Party Strategies', content: 'Planning parties for autistic children.', link: 'https://www.autism.org/birthday-parties/', category: 'SOCIAL_SKILLS' },
  { title: 'Swimming and Water Safety', content: 'Water safety for autism families.', link: 'https://nationalautismassociation.org/resources/autism-safety-facts/wandering/', category: 'OTHER' },
  { title: 'Driving and Autism', content: 'Resources for autistic drivers and learners.', link: 'https://www.autism.org/driving-and-autism/', category: 'OTHER' },
  { title: 'Dating and Relationships', content: 'Support for autistic teens and adults.', link: 'https://www.autism.org/relationships-and-autism/', category: 'SOCIAL_SKILLS' },
  { title: 'College Planning', content: 'Preparing for higher education.', link: 'https://www.understood.org/en/articles/college-planning-for-students-with-autism', category: 'EDUCATION' },
  { title: 'Employment Preparation', content: 'Job readiness for autistic adults.', link: 'https://www.autism-society.org/living-with-autism/transition-to-adulthood/employment/', category: 'COMMUNITY' },
  { title: 'Independent Living', content: 'Resources for living independently.', link: 'https://www.autism-society.org/living-with-autism/transition-to-adulthood/housing/', category: 'COMMUNITY' },
  { title: 'Crisis Resources', content: 'Emergency and crisis support information.', link: 'https://www.autism.org/crisis-and-emergency-resources/', category: 'COMMUNITY' },
  { title: 'Self-Care for Parents', content: 'Managing stress and caregiver burnout.', link: 'https://www.autism.org/parent-burnout/', category: 'COMMUNITY' },
  { title: 'Sibling Resources', content: 'Supporting siblings of autistic children.', link: 'https://www.siblingsupport.org/about-sibs', category: 'COMMUNITY' },
  { title: 'Respite Care', content: 'Finding respite and backup care.', link: 'https://www.archrespite.org/', category: 'COMMUNITY' },
  { title: 'Medicaid Waivers', content: 'State waiver programs for autism services.', link: 'https://www.medicaid.gov/medicaid/home-community-based-services/home-community-based-services-authorities/index.html', category: 'FINANCIAL' },
  { title: 'Autism and COVID-19', content: 'Pandemic resources and updates.', link: 'https://www.autismspeaks.org/covid-19-information-and-resources', category: 'OTHER' },
  { title: 'Teletherapy Tips', content: 'Making virtual therapy work for your child.', link: 'https://www.asha.org/practice-portal/clinical-topics/telepractice/', category: 'THERAPY' },
  { title: 'Assistive Technology', content: 'AT tools for communication and learning.', link: 'https://www.atia.org/', category: 'THERAPY' },
];

export const RESOURCE_COUNT = STATIC_RESOURCES.length;
