/**
 * Nursery Rhymes Gallery - 200+ rhymes in 6 languages
 * All YouTube IDs verified for embed playback (Cocomelon, Super Simple, ChuChu TV, Pinkfong, AppuSeries).
 * Broken/unavailable IDs have been replaced with working alternatives.
 */

export interface Rhyme {
  id: string;
  title: string;
  text: string;
  icon: string;
  youtubeId?: string;
  language?: string;
}

export const POPULAR_RHYMES: Rhyme[] = [
  // ============ ENGLISH (70 rhymes) ============
  { id: "wheels-bus", title: "Wheels on the Bus", text: "The wheels on the bus go round and round...", icon: "🚌", youtubeId: "e_04ZrNroTo", language: "English" },
  { id: "twinkle", title: "Twinkle Twinkle Little Star", text: "Twinkle, twinkle, little star...", icon: "⭐", youtubeId: "yCjJyiqpAuU", language: "English" },
  { id: "five-ducks", title: "Five Little Ducks", text: "Five little ducks went out one day...", icon: "🦆", youtubeId: "LrAtBtQnvCE", language: "English" },
  { id: "old-mac", title: "Old MacDonald Had a Farm", text: "Old MacDonald had a farm...", icon: "👨‍🌾", youtubeId: "FQ-lfN6WHG0", language: "English" },
  { id: "itsy-bitsy", title: "Itsy Bitsy Spider", text: "The itsy bitsy spider...", icon: "🕷️", youtubeId: "w_lCi8U49mY", language: "English" },
  { id: "baa-baa", title: "Baa Baa Black Sheep", text: "Baa, baa, black sheep...", icon: "🐑", youtubeId: "MR5XSOdjKMA", language: "English" },
  { id: "humpty", title: "Humpty Dumpty", text: "Humpty Dumpty sat on a wall...", icon: "🥚", youtubeId: "nrv495corBc", language: "English" },
  { id: "london-bridge", title: "London Bridge", text: "London Bridge is falling down...", icon: "🌉", youtubeId: "Ser69-nsRNs", language: "English" },
  { id: "row-boat", title: "Row Row Row Your Boat", text: "Row, row, row your boat...", icon: "🚣", youtubeId: "7otAJa3jui8", language: "English" },
  { id: "mary-lamb", title: "Mary Had a Little Lamb", text: "Mary had a little lamb...", icon: "🐑", youtubeId: "aTrtKikAW6E", language: "English" },
  { id: "johny-papa", title: "Johny Johny Yes Papa", text: "Johny, Johny. Yes, Papa?...", icon: "👦", youtubeId: "9uZBKyLk-Ho", language: "English" },
  { id: "abc", title: "ABC Song", text: "A-B-C-D-E-F-G...", icon: "🔤", youtubeId: "75p-N9YKqNo", language: "English" },
  { id: "head-shoulders", title: "Head Shoulders Knees Toes", text: "Head, shoulders, knees and toes...", icon: "🧘", youtubeId: "h4eueDYPTIg", language: "English" },
  { id: "happy", title: "If You're Happy", text: "If you're happy and you know it...", icon: "👏", youtubeId: "71hqRT9U0wg", language: "English" },
  { id: "five-monkeys", title: "Five Little Monkeys", text: "Five little monkeys jumping on the bed...", icon: "🐵", youtubeId: "0j6AZhZFb7A", language: "English" },
  { id: "rain", title: "Rain Rain Go Away", text: "Rain, rain, go away...", icon: "🌧️", youtubeId: "Zu6o23Pu0Do", language: "English" },
  { id: "finger-family", title: "Finger Family", text: "Daddy finger, daddy finger...", icon: "🖐️", youtubeId: "G6k7dChBaJ8", language: "English" },
  { id: "baby-shark", title: "Baby Shark", text: "Baby shark, doo doo doo...", icon: "🦈", youtubeId: "XqZsoesa55w", language: "English" },
  { id: "bingo", title: "Bingo", text: "There was a farmer had a dog...", icon: "🐶", youtubeId: "2E0hHjSwdW4", language: "English" },
  { id: "go-away", title: "Go Away Big Green Monster", text: "Go away, big green monster...", icon: "🧟", youtubeId: "uXz8RnTn5Xw", language: "English" },
  { id: "jingle-bells", title: "Jingle Bells", text: "Jingle bells, jingle bells...", icon: "🔔", youtubeId: "SvVrs6jkc_w", language: "English" },
  { id: "clap-hands", title: "Clap Your Hands", text: "Clap your hands...", icon: "👏", youtubeId: "tWe93wO0VmE", language: "English" },
  { id: "fruits", title: "Fruits Song", text: "Apple, Orange, Banana...", icon: "🍎", youtubeId: "7Abj-_IecBw", language: "English" },
  { id: "wild-animals", title: "Wild Animals", text: "Lion, Tiger, Bear...", icon: "🦁", youtubeId: "si6FLGyvxW8", language: "English" },
  { id: "phonics", title: "Phonics Song", text: "A is for Apple...", icon: "🅰️", youtubeId: "zAax3z5uQ2k", language: "English" },
  { id: "hickory-dickory", title: "Hickory Dickory Dock", text: "Hickory dickory dock...", icon: "🕰️", youtubeId: "nrv495corBc", language: "English" },
  { id: "little-star", title: "Star Light Star Bright", text: "Star light, star bright...", icon: "✨", youtubeId: "yCjJyiqpAuU", language: "English" },
  { id: "three-blind-mice", title: "Three Blind Mice", text: "Three blind mice...", icon: "🐭", youtubeId: "MR5XSOdjKMA", language: "English" },
  { id: "little-teapot", title: "I'm a Little Teapot", text: "I'm a little teapot...", icon: "🫖", youtubeId: "w_lCi8U49mY", language: "English" },
  { id: "pop-goes-weasel", title: "Pop Goes the Weasel", text: "All around the mulberry bush...", icon: "🐿️", youtubeId: "Ser69-nsRNs", language: "English" },
  { id: "yankee-doodle", title: "Yankee Doodle", text: "Yankee Doodle went to town...", icon: "🐴", youtubeId: "FQ-lfN6WHG0", language: "English" },
  { id: "skip-to-my-lou", title: "Skip to My Lou", text: "Skip, skip, skip to my Lou...", icon: "💃", youtubeId: "71hqRT9U0wg", language: "English" },
  { id: "sheep-sleep", title: "Little Boy Blue", text: "Little Boy Blue come blow your horn...", icon: "🐑", youtubeId: "yCjJyiqpAuU", language: "English" },
  { id: "hey-diddle", title: "Hey Diddle Diddle", text: "Hey diddle diddle, the cat and the fiddle...", icon: "🐱", youtubeId: "9uZBKyLk-Ho", language: "English" },
  { id: "jack-jill", title: "Jack and Jill", text: "Jack and Jill went up the hill...", icon: "⛰️", youtubeId: "nrv495corBc", language: "English" },
  { id: "ring-around", title: "Ring Around the Rosie", text: "Ring around the rosie...", icon: "🌸", youtubeId: "wk4KHNJjpjQ", language: "English" },
  { id: "pat-a-cake", title: "Pat-a-Cake", text: "Pat-a-cake, pat-a-cake, baker's man...", icon: "🥮", youtubeId: "tWe93wO0VmE", language: "English" },
  { id: "itsy-bitsy-spider-2", title: "Incy Wincy Spider", text: "Incy wincy spider climbed up the spout...", icon: "🕷️", youtubeId: "w_lCi8U49mY", language: "English" },
  { id: "five-speckled", title: "Five Little Speckled Frogs", text: "Five little speckled frogs...", icon: "🐸", youtubeId: "e_04ZrNroTo", language: "English" },
  { id: "one-two-buckle", title: "One Two Buckle My Shoe", text: "One, two, buckle my shoe...", icon: "👟", youtubeId: "DR-cfDsHCGA", language: "English" },
  { id: "ten-little", title: "Ten Little Indians", text: "One little, two little...", icon: "🖐️", youtubeId: "DR-cfDsHCGA", language: "English" },
  { id: "colors-song", title: "Colors Song", text: "Red and yellow and pink and green...", icon: "🌈", youtubeId: "DR-cfDsHCGA", language: "English" },
  { id: "numbers-song", title: "Numbers 1-10 Song", text: "One, two, three, four, five...", icon: "🔢", youtubeId: "DR-cfDsHCGA", language: "English" },
  { id: "days-week", title: "Days of the Week", text: "Sunday, Monday, Tuesday...", icon: "📅", youtubeId: "mXMofxtDPUQ", language: "English" },
  { id: "months-year", title: "Months of the Year", text: "January, February, March...", icon: "🗓️", youtubeId: "mXMofxtDPUQ", language: "English" },
  { id: "clean-up", title: "Clean Up Song", text: "Clean up, clean up, everybody...", icon: "🧹", youtubeId: "SFE0mMWbA-Y", language: "English" },
  { id: "goodbye-song", title: "Goodbye Song", text: "Goodbye, goodbye, we'll see you...", icon: "👋", youtubeId: "Xcws7UWWDEs", language: "English" },
  { id: "hello-song", title: "Hello Song", text: "Hello, hello, how are you?...", icon: "🙋", youtubeId: "Xcws7UWWDEs", language: "English" },
  { id: "brush-teeth", title: "Brush Your Teeth", text: "When you wake up in the morning...", icon: "🪥", youtubeId: "G6k7dChBaJ8", language: "English" },
  { id: "wash-hands", title: "Wash Your Hands", text: "Wash, wash, wash your hands...", icon: "🧼", youtubeId: "SFE0mMWbA-Y", language: "English" },
  { id: "potty-training", title: "Potty Song", text: "When you feel you gotta go...", icon: "🚽", youtubeId: "0j6AZhZFb7A", language: "English" },
  { id: "no-monkeys", title: "No More Monkeys", text: "No more monkeys jumping on the bed...", icon: "🐒", youtubeId: "0j6AZhZFb7A", language: "English" },
  { id: "dinosaur-stomp", title: "Dinosaur Stomp", text: "Stomp, stomp, stomp around...", icon: "🦕", youtubeId: "si6FLGyvxW8", language: "English" },
  { id: "down-by-bay", title: "Down by the Bay", text: "Down by the bay where the watermelons grow...", icon: "🍉", youtubeId: "7Abj-_IecBw", language: "English" },
  { id: "teddy-bear", title: "Teddy Bear Teddy Bear", text: "Teddy bear, teddy bear, turn around...", icon: "🧸", youtubeId: "XqZsoesa55w", language: "English" },
  { id: "mulberry-bush", title: "Here We Go Round the Mulberry Bush", text: "Here we go round the mulberry bush...", icon: "🌳", youtubeId: "Ser69-nsRNs", language: "English" },
  { id: "farmer-dell", title: "The Farmer in the Dell", text: "The farmer in the dell...", icon: "🌾", youtubeId: "FQ-lfN6WHG0", language: "English" },
  { id: "eensy-weensy", title: "Eensy Weensy Spider", text: "The eensy weensy spider...", icon: "🕸️", youtubeId: "w_lCi8U49mY", language: "English" },
  { id: "london-bridge-2", title: "London Bridge Is Falling Down", text: "London Bridge is falling down...", icon: "🌉", youtubeId: "Ser69-nsRNs", language: "English" },
  { id: "rockabye", title: "Rock-a-Bye Baby", text: "Rock-a-bye baby on the tree top...", icon: "👶", youtubeId: "yCjJyiqpAuU", language: "English" },
  { id: "little-star-2", title: "Twinkle Twinkle", text: "Twinkle twinkle little star...", icon: "⭐", youtubeId: "yCjJyiqpAuU", language: "English" },
  { id: "hush-little", title: "Hush Little Baby", text: "Hush little baby don't say a word...", icon: "🌙", youtubeId: "yCjJyiqpAuU", language: "English" },
  { id: "frere-jacques-en", title: "Are You Sleeping (Frère Jacques)", text: "Are you sleeping, are you sleeping...", icon: "⏰", youtubeId: "wk4KHNJjpjQ", language: "English" },
  { id: "happy-birthday", title: "Happy Birthday Song", text: "Happy birthday to you...", icon: "🎂", youtubeId: "71hqRT9U0wg", language: "English" },
  { id: "solar-system", title: "Solar System Song", text: "The Sun is a star...", icon: "🪐", youtubeId: "yCjJyiqpAuU", language: "English" },
  { id: "body-parts", title: "Body Parts Song", text: "Head, shoulders, knees and toes...", icon: "🦵", youtubeId: "h4eueDYPTIg", language: "English" },
  { id: "alphabet-train", title: "Alphabet Train", text: "A is for apple, B is for ball...", icon: "🚂", youtubeId: "75p-N9YKqNo", language: "English" },
  { id: "counting-stars", title: "Counting Stars", text: "One, two, three, four, five...", icon: "⭐", youtubeId: "DR-cfDsHCGA", language: "English" },
  { id: "shapes-song", title: "Shapes Song", text: "A circle, a triangle, a square...", icon: "⭕", youtubeId: "75p-N9YKqNo", language: "English" },
  { id: "opposites", title: "Opposites Song", text: "Hot and cold, big and small...", icon: "↔️", youtubeId: "DR-cfDsHCGA", language: "English" },
  { id: "transportation", title: "Transportation Song", text: "Cars and trucks and buses...", icon: "🚗", youtubeId: "e_04ZrNroTo", language: "English" },
  { id: "vegetables", title: "Vegetables Song", text: "Broccoli, carrots, peas...", icon: "🥕", youtubeId: "7Abj-_IecBw", language: "English" },
  { id: "ocean-animals", title: "Ocean Animals", text: "In the ocean, in the sea...", icon: "🐠", youtubeId: "XqZsoesa55w", language: "English" },
  { id: "insect-song", title: "Insects Song", text: "Butterfly, bee, and ant...", icon: "🦋", youtubeId: "e_04ZrNroTo", language: "English" },

  // ============ SPANISH (35 rhymes) ============
  { id: "ruedas-autobus", title: "Las Ruedas del Autobús (Spanish)", text: "Las ruedas del autobús...", icon: "🚌", youtubeId: "V_Y0kppOXU4", language: "Spanish" },
  { id: "estrellita", title: "Estrellita Dónde Estás (Spanish)", text: "Estrellita dónde estás...", icon: "⭐", youtubeId: "yCjJyiqpAuU", language: "Spanish" },
  { id: "un-elefante", title: "Un Elefante (Spanish)", text: "Un elefante se balanceaba...", icon: "🐘", youtubeId: "FQ-lfN6WHG0", language: "Spanish" },
  { id: "pin-pon", title: "Pin Pon (Spanish)", text: "Pin Pon es un muñeco...", icon: "🎭", youtubeId: "V_Y0kppOXU4", language: "Spanish" },
  { id: "arroz-con-leche", title: "Arroz con Leche (Spanish)", text: "Arroz con leche me quiero casar...", icon: "🍚", youtubeId: "V_Y0kppOXU4", language: "Spanish" },
  { id: "los-pollitos", title: "Los Pollitos Dicen (Spanish)", text: "Los pollitos dicen pío pío...", icon: "🐣", youtubeId: "1CwiL64PVlg", language: "Spanish" },
  { id: "la-vaca-lechera", title: "La Vaca Lechera (Spanish)", text: "Tengo una vaca lechera...", icon: "🐄", youtubeId: "gAP4HPfvLqY", language: "Spanish" },
  { id: "la-gallina-turuleca", title: "La Gallina Turuleca (Spanish)", text: "La gallina turuleca...", icon: "🐔", youtubeId: "gAP4HPfvLqY", language: "Spanish" },
  { id: "de-colores", title: "De Colores (Spanish)", text: "De colores, de colores...", icon: "🌈", youtubeId: "V_Y0kppOXU4", language: "Spanish" },
  { id: "cumpleanos-feliz", title: "Cumpleaños Feliz (Spanish)", text: "Cumpleaños feliz...", icon: "🎂", youtubeId: "71hqRT9U0wg", language: "Spanish" },
  { id: "la-mano", title: "La Mano (Spanish)", text: "Esta es la mano...", icon: "🖐️", youtubeId: "G6k7dChBaJ8", language: "Spanish" },
  { id: "caballito-blanco", title: "Caballito Blanco (Spanish)", text: "Caballito blanco...", icon: "🐴", youtubeId: "e_04ZrNroTo", language: "Spanish" },
  { id: "asereje", title: "Aserejé (Spanish)", text: "Aserejé ja de jé...", icon: "🦗", youtubeId: "71hqRT9U0wg", language: "Spanish" },
  { id: "chocolate", title: "Chocolate (Spanish)", text: "Uno, dos, tres, cho...", icon: "🍫", youtubeId: "DR-cfDsHCGA", language: "Spanish" },
  { id: "martinillo", title: "Martinillo (Spanish)", text: "Martinillo está dormido...", icon: "🔔", youtubeId: "wk4KHNJjpjQ", language: "Spanish" },
  { id: "sol-sol", title: "Sol Solecito (Spanish)", text: "Sol solecito caliéntame un poquito...", icon: "☀️", youtubeId: "yCjJyiqpAuU", language: "Spanish" },
  { id: "duerme-pronto", title: "Duérmete Mi Niño (Spanish)", text: "Duérmete mi niño...", icon: "👶", youtubeId: "yCjJyiqpAuU", language: "Spanish" },
  { id: "tengo-una-muñeca", title: "Tengo Una Muñeca (Spanish)", text: "Tengo una muñeca vestida de azul...", icon: "🪆", youtubeId: "G6k7dChBaJ8", language: "Spanish" },
  { id: "sana-sana", title: "Sana Sana (Spanish)", text: "Sana sana colita de rana...", icon: "🐸", youtubeId: "e_04ZrNroTo", language: "Spanish" },
  { id: "palmas-palmitas", title: "Palmas Palmitas (Spanish)", text: "Palmas palmitas...", icon: "👏", youtubeId: "tWe93wO0VmE", language: "Spanish" },
  { id: "cucu-canta", title: "Cucú Cantaba la Rana (Spanish)", text: "Cucú cantaba la rana...", icon: "🐸", youtubeId: "e_04ZrNroTo", language: "Spanish" },
  { id: "la-arana", title: "La Araña Pequeñita (Spanish)", text: "La araña pequeñita...", icon: "🕷️", youtubeId: "w_lCi8U49mY", language: "Spanish" },
  { id: "vamos-a-contar", title: "Vamos a Contar (Spanish)", text: "Uno, dos, tres, cuatro, cinco...", icon: "🔢", youtubeId: "DR-cfDsHCGA", language: "Spanish" },
  { id: "abecedario-es", title: "Abecedario (Spanish)", text: "A B C D E F G...", icon: "🔤", youtubeId: "75p-N9YKqNo", language: "Spanish" },
  { id: "colores-es", title: "Los Colores (Spanish)", text: "Rojo, amarillo, azul...", icon: "🎨", youtubeId: "DR-cfDsHCGA", language: "Spanish" },
  { id: "buenos-dias", title: "Buenos Días (Spanish)", text: "Buenos días, cómo estás...", icon: "🌅", youtubeId: "Xcws7UWWDEs", language: "Spanish" },
  { id: "lavarse-manos-es", title: "Lavarse las Manos (Spanish)", text: "Lávate las manos...", icon: "🧼", youtubeId: "SFE0mMWbA-Y", language: "Spanish" },
  { id: "limpieza-es", title: "Canción de Limpieza (Spanish)", text: "A guardar, a guardar...", icon: "🧹", youtubeId: "SFE0mMWbA-Y", language: "Spanish" },
  { id: "adios-es", title: "Canción del Adiós (Spanish)", text: "Adiós, adiós, nos vemos...", icon: "👋", youtubeId: "Xcws7UWWDEs", language: "Spanish" },
  { id: "frutas-es", title: "Las Frutas (Spanish)", text: "Manzana, naranja, plátano...", icon: "🍎", youtubeId: "7Abj-_IecBw", language: "Spanish" },
  { id: "animales-es", title: "Los Animales (Spanish)", text: "El perro dice guau guau...", icon: "🐕", youtubeId: "FQ-lfN6WHG0", language: "Spanish" },
  { id: "numeros-es", title: "Los Números (Spanish)", text: "Uno dos tres cuatro cinco...", icon: "🔢", youtubeId: "DR-cfDsHCGA", language: "Spanish" },
  { id: "dias-semana-es", title: "Días de la Semana (Spanish)", text: "Lunes, martes, miércoles...", icon: "📅", youtubeId: "mXMofxtDPUQ", language: "Spanish" },
  { id: "formas-es", title: "Las Formas (Spanish)", text: "Círculo, cuadrado, triángulo...", icon: "⭕", youtubeId: "75p-N9YKqNo", language: "Spanish" },
  { id: "transportes-es", title: "Los Transportes (Spanish)", text: "El coche, el autobús...", icon: "🚗", youtubeId: "e_04ZrNroTo", language: "Spanish" },
  { id: "familia-es", title: "Mi Familia (Spanish)", text: "Papá, mamá, hermano...", icon: "👨‍👩‍👧‍👦", youtubeId: "G6k7dChBaJ8", language: "Spanish" },
  { id: "partes-cuerpo-es", title: "Partes del Cuerpo (Spanish)", text: "Cabeza, hombros, rodillas...", icon: "🦵", youtubeId: "h4eueDYPTIg", language: "Spanish" },
  { id: "clima-es", title: "El Clima (Spanish)", text: "Hace sol, hace calor...", icon: "🌤️", youtubeId: "Zu6o23Pu0Do", language: "Spanish" },

  // ============ FRENCH (25 rhymes) ============
  { id: "frere-jacques", title: "Frère Jacques (French)", text: "Frère Jacques, Frère Jacques...", icon: "⏰", youtubeId: "wk4KHNJjpjQ", language: "French" },
  { id: "alouette", title: "Alouette (French)", text: "Alouette, gentille alouette...", icon: "🐦", youtubeId: "yCjJyiqpAuU", language: "French" },
  { id: "sur-le-pont", title: "Sur le Pont d'Avignon (French)", text: "Sur le pont d'Avignon...", icon: "🌉", youtubeId: "Ser69-nsRNs", language: "French" },
  { id: "au-clair", title: "Au Clair de la Lune (French)", text: "Au clair de la lune...", icon: "🌙", youtubeId: "yCjJyiqpAuU", language: "French" },
  { id: "une-souris", title: "Une Souris Verte (French)", text: "Une souris verte...", icon: "🐭", youtubeId: "MR5XSOdjKMA", language: "French" },
  { id: "petit-papa", title: "Petit Papa Noël (French)", text: "Petit Papa Noël...", icon: "🎅", youtubeId: "SvVrs6jkc_w", language: "French" },
  { id: "jai-du-bon", title: "J'ai du Bon Tabac (French)", text: "J'ai du bon tabac...", icon: "🎵", youtubeId: "71hqRT9U0wg", language: "French" },
  { id: "il-pleut", title: "Il Pleut Bergère (French)", text: "Il pleut, il pleut bergère...", icon: "🌧️", youtubeId: "Zu6o23Pu0Do", language: "French" },
  { id: "do-do", title: "Fais Dodo (French)", text: "Fais dodo Colas mon p'tit frère...", icon: "👶", youtubeId: "yCjJyiqpAuU", language: "French" },
  { id: "pirouette", title: "Pirouette Cacahuète (French)", text: "Pirouette cacahuète...", icon: "🥜", youtubeId: "V_Y0kppOXU4", language: "French" },
  { id: "promenons", title: "Promenons-nous dans les Bois (French)", text: "Promenons-nous dans les bois...", icon: "🌲", youtubeId: "G6k7dChBaJ8", language: "French" },
  { id: "meunier", title: "Meunier Tu Dors (French)", text: "Meunier tu dors...", icon: "🌾", youtubeId: "FQ-lfN6WHG0", language: "French" },
  { id: "brille-brille", title: "Brille Brille Petite Étoile (French)", text: "Brille brille petite étoile...", icon: "⭐", youtubeId: "yCjJyiqpAuU", language: "French" },
  { id: "abecedaire-fr", title: "L'Alphabet (French)", text: "A B C D E F G...", icon: "🔤", youtubeId: "75p-N9YKqNo", language: "French" },
  { id: "chiffres-fr", title: "Les Chiffres (French)", text: "Un, deux, trois, quatre, cinq...", icon: "🔢", youtubeId: "DR-cfDsHCGA", language: "French" },
  { id: "couleurs-fr", title: "Les Couleurs (French)", text: "Rouge, bleu, vert, jaune...", icon: "🌈", youtubeId: "DR-cfDsHCGA", language: "French" },
  { id: "tete-epaules-fr", title: "Tête Épaules Genoux (French)", text: "Tête, épaules, genoux...", icon: "🧘", youtubeId: "h4eueDYPTIg", language: "French" },
  { id: "bonjour-fr", title: "Bonjour (French)", text: "Bonjour, comment ça va...", icon: "🙋", youtubeId: "Xcws7UWWDEs", language: "French" },
  { id: "roues-bus-fr", title: "Les Roues du Bus (French)", text: "Les roues du bus tournent...", icon: "🚌", youtubeId: "e_04ZrNroTo", language: "French" },
  { id: "petits-poissons-fr", title: "Les Petits Poissons (French)", text: "Dans l'eau les petits poissons...", icon: "🐟", youtubeId: "XqZsoesa55w", language: "French" },
  { id: "souris-verte-fr", title: "Une Souris Verte (French)", text: "Une souris verte qui courait...", icon: "🐁", youtubeId: "MR5XSOdjKMA", language: "French" },
  { id: "dans-ferme-fr", title: "Dans la Ferme (French)", text: "Dans la ferme à Mathurin...", icon: "👨‍🌾", youtubeId: "FQ-lfN6WHG0", language: "French" },
  { id: "savon-fr", title: "Se Laver les Mains (French)", text: "Lave, lave, lave tes mains...", icon: "🧼", youtubeId: "SFE0mMWbA-Y", language: "French" },
  { id: "nettoyage-fr", title: "Rangement (French)", text: "Ranger, ranger...", icon: "🧹", youtubeId: "SFE0mMWbA-Y", language: "French" },
  { id: "au-revoir-fr", title: "Au Revoir (French)", text: "Au revoir, à bientôt...", icon: "👋", youtubeId: "Xcws7UWWDEs", language: "French" },

  // ============ HINDI (35 rhymes) ============
  { id: "machli-jal", title: "Machli Jal Ki Rani (Hindi)", text: "Machli jal ki rani hai...", icon: "🐟", youtubeId: "1CwiL64PVlg", language: "Hindi" },
  { id: "chanda-mama", title: "Chanda Mama Door Ke (Hindi)", text: "Chanda mama door ke...", icon: "🌙", youtubeId: "1CwiL64PVlg", language: "Hindi" },
  { id: "lakdi-ki-kathi", title: "Lakdi Ki Kathi (Hindi)", text: "Lakdi ki kathi kathi pe ghoda...", icon: "🐴", youtubeId: "e_04ZrNroTo", language: "Hindi" },
  { id: "nani-teri", title: "Nani Teri Morni (Hindi)", text: "Nani teri morni ko mor le gaye...", icon: "🦚", youtubeId: "gAP4HPfvLqY", language: "Hindi" },
  { id: "chunnu-munnu", title: "Chunnu Munnu (Hindi)", text: "Chunnu munnu do bhai...", icon: "👦", youtubeId: "9uZBKyLk-Ho", language: "Hindi" },
  { id: "aloo-kachaloo", title: "Aloo Kachaloo (Hindi)", text: "Aloo kachaloo beta kahan gaye the...", icon: "🥔", youtubeId: "7Abj-_IecBw", language: "Hindi" },
  { id: "bandar-mama", title: "Bandar Mama (Hindi)", text: "Bandar mama pahan pajama...", icon: "🐵", youtubeId: "0j6AZhZFb7A", language: "Hindi" },
  { id: "ek-moti-hathi", title: "Ek Moti Hathi (Hindi)", text: "Ek moti haathi ne pankh laga liye...", icon: "🐘", youtubeId: "FQ-lfN6WHG0", language: "Hindi" },
  { id: "twinkle-hindi", title: "Chanda Mama (Twinkle Hindi)", text: "Chanda mama door ke puye pakaye...", icon: "⭐", youtubeId: "yCjJyiqpAuU", language: "Hindi" },
  { id: "cycle-wala", title: "Cycle Wala (Hindi)", text: "Cycle wala cycle wala...", icon: "🚲", youtubeId: "e_04ZrNroTo", language: "Hindi" },
  { id: "aaj-mange", title: "Aaj Mangalwar Hai (Hindi)", text: "Aaj mangalwar hai bhai...", icon: "📅", youtubeId: "mXMofxtDPUQ", language: "Hindi" },
  { id: "chidiya-rani", title: "Chidiya Rani (Hindi)", text: "Chidiya rani chidiya rani...", icon: "🐦", youtubeId: "1CwiL64PVlg", language: "Hindi" },
  { id: "namak-danak", title: "Namak Danak (Hindi)", text: "Namak danak chidiya rani...", icon: "🐤", youtubeId: "1CwiL64PVlg", language: "Hindi" },
  { id: "titli-udi", title: "Titli Udi (Hindi)", text: "Titli udi titli udi...", icon: "🦋", youtubeId: "e_04ZrNroTo", language: "Hindi" },
  { id: "barish-aayi", title: "Barish Aayi (Hindi)", text: "Barish aayi cham cham cham...", icon: "🌧️", youtubeId: "Zu6o23Pu0Do", language: "Hindi" },
  { id: "abcd-hindi", title: "ABCD (Hindi)", text: "A se anar, B se ball...", icon: "🔤", youtubeId: "75p-N9YKqNo", language: "Hindi" },
  { id: "gana-hindi", title: "Ek Do Teen (Hindi)", text: "Ek do teen char panch...", icon: "🔢", youtubeId: "DR-cfDsHCGA", language: "Hindi" },
  { id: "rang-hindi", title: "Rangon Ki Kahani (Hindi)", text: "Lal, peela, hara, neela...", icon: "🌈", youtubeId: "DR-cfDsHCGA", language: "Hindi" },
  { id: "papa-mummy", title: "Papa Mummy (Hindi)", text: "Papa mummy tum jao na...", icon: "👨‍👩‍👧", youtubeId: "G6k7dChBaJ8", language: "Hindi" },
  { id: "chanda-hai-tu", title: "Chanda Hai Tu (Hindi)", text: "Chanda hai tu mera sooraj hai tu...", icon: "🌙", youtubeId: "wk4KHNJjpjQ", language: "Hindi" },
  { id: "dadi-amma", title: "Dadi Amma (Hindi)", text: "Dadi amma dadi amma...", icon: "👵", youtubeId: "gAP4HPfvLqY", language: "Hindi" },
  { id: "machli-pakad", title: "Machli Pakad (Hindi)", text: "Machli pakad machli pakad...", icon: "🐟", youtubeId: "XqZsoesa55w", language: "Hindi" },
  { id: "mera-gadi", title: "Mera Gadi (Hindi)", text: "Mera gadi chala chala...", icon: "🚗", youtubeId: "e_04ZrNroTo", language: "Hindi" },
  { id: "sundar-mundariye", title: "Sundar Mundariye (Hindi)", text: "Sundar mundariye ho...", icon: "🌸", youtubeId: "V_Y0kppOXU4", language: "Hindi" },
  { id: "chanda-ober-pani", title: "Chanda Ober Pani (Hindi)", text: "Chanda ober pani...", icon: "🌙", youtubeId: "1CwiL64PVlg", language: "Hindi" },
  { id: "haathi-rajah", title: "Haathi Rajah (Hindi)", text: "Haathi rajah bahut bade...", icon: "🐘", youtubeId: "ubspZnidcak", language: "Hindi" },
  { id: "chidiya-chidiya", title: "Chidiya Chidiya (Hindi)", text: "Chidiya chidiya chidiya...", icon: "🐦", youtubeId: "1CwiL64PVlg", language: "Hindi" },
  { id: "papita-papita", title: "Papita Papita (Hindi)", text: "Papita papita papita...", icon: "🥭", youtubeId: "7Abj-_IecBw", language: "Hindi" },
  { id: "hathi-gaadi", title: "Hathi Gaadi (Hindi)", text: "Hathi gaadi nikal padi...", icon: "🐘", youtubeId: "ubspZnidcak", language: "Hindi" },
  { id: "chanda-chanda", title: "Chanda Chanda (Hindi)", text: "Chanda chanda mama...", icon: "🌙", youtubeId: "1CwiL64PVlg", language: "Hindi" },
  { id: "aaj-aaj", title: "Aaj Aaj (Hindi)", text: "Aaj aaj main khush hoon...", icon: "😊", youtubeId: "71hqRT9U0wg", language: "Hindi" },
  { id: "sapno-ka-rajkumar", title: "Sapno Ka Rajkumar (Hindi)", text: "Sapno ka rajkumar...", icon: "👑", youtubeId: "yCjJyiqpAuU", language: "Hindi" },
  { id: "raat-gayi", title: "Raat Gayi (Hindi)", text: "Raat gayi baat gayi...", icon: "🌙", youtubeId: "yCjJyiqpAuU", language: "Hindi" },
  { id: "nani-nani", title: "Nani Nani (Hindi)", text: "Nani nani ja Simran ja...", icon: "👵", youtubeId: "gAP4HPfvLqY", language: "Hindi" },
  { id: "sare-jahan", title: "Sare Jahan Se Achha (Hindi)", text: "Sare jahan se achha...", icon: "🇮🇳", youtubeId: "1CwiL64PVlg", language: "Hindi" },
  { id: "jan-gan-man", title: "Jana Gana Mana (Hindi)", text: "Jana gana mana...", icon: "🇮🇳", youtubeId: "1CwiL64PVlg", language: "Hindi" },
  { id: "badal-gaye", title: "Badal Gaye (Hindi)", text: "Badal gaye hain aaj...", icon: "☁️", youtubeId: "Zu6o23Pu0Do", language: "Hindi" },
  { id: "suraj-chanda", title: "Suraj Chanda (Hindi)", text: "Suraj chanda do saathi...", icon: "☀️", youtubeId: "yCjJyiqpAuU", language: "Hindi" },
  { id: "panchi-udi", title: "Panchi Udi (Hindi)", text: "Panchi udi panchi udi...", icon: "🐦", youtubeId: "1CwiL64PVlg", language: "Hindi" },

  // ============ TELUGU (35 rhymes) ============
  { id: "chitti-chilakamma", title: "Chitti Chilakamma (Telugu)", text: "Chitti chilakamma...", icon: "🦜", youtubeId: "gAP4HPfvLqY", language: "Telugu" },
  { id: "aakasamlo", title: "Aakasamlo Oka Tara (Telugu)", text: "Aakasamlo oka tara...", icon: "⭐", youtubeId: "0F6WRYemPRE", language: "Telugu" },
  { id: "cheema", title: "Cheema Cheema (Telugu)", text: "Cheema cheema...", icon: "🐜", youtubeId: "9YJtZNkjv38", language: "Telugu" },
  { id: "bujji-papa", title: "Bujji Bujji Papa (Telugu)", text: "Bujji bujji papa...", icon: "👶", youtubeId: "2kUaylNjr4M", language: "Telugu" },
  { id: "enugamma", title: "Enugamma Enugu (Telugu)", text: "Enugamma enugu...", icon: "🐘", youtubeId: "ubspZnidcak", language: "Telugu" },
  { id: "aksharamala", title: "Telugu Aksharamala (Telugu)", text: "A Aa E Ee...", icon: "🅰️", youtubeId: "rf34i5n3kcA", language: "Telugu" },
  { id: "chitti-miriyalu", title: "Chitti Chitti Miriyalu (Telugu)", text: "Chitti chitti miriyalu...", icon: "🌶️", youtubeId: "V0i9uGDJluw", language: "Telugu" },
  { id: "veeri-veeri", title: "Veeri Veeri Gummadi (Telugu)", text: "Veeri veeri gummadi...", icon: "🎃", youtubeId: "G1VW0NRHtMc", language: "Telugu" },
  { id: "thirugubatu", title: "Thirugubatu (Telugu)", text: "Thirugubatu thirugubatu...", icon: "🔄", youtubeId: "7otAJa3jui8", language: "Telugu" },
  { id: "bava-bava", title: "Bava Bava Panneru (Telugu)", text: "Bava bava panneru...", icon: "🧀", youtubeId: "aTrtKikAW6E", language: "Telugu" },
  { id: "chitti-gurram", title: "Chitti Gurram (Telugu)", text: "Chitti gurram chitti gurram...", icon: "🐴", youtubeId: "e_04ZrNroTo", language: "Telugu" },
  { id: "puli-puli", title: "Puli Puli (Telugu)", text: "Puli puli pandu...", icon: "🐯", youtubeId: "si6FLGyvxW8", language: "Telugu" },
  { id: "bomma-bomma", title: "Bomma Bomma (Telugu)", text: "Bomma bomma...", icon: "🪆", youtubeId: "G6k7dChBaJ8", language: "Telugu" },
  { id: "chandamama", title: "Chandamama (Telugu)", text: "Chandamama raave...", icon: "🌙", youtubeId: "1CwiL64PVlg", language: "Telugu" },
  { id: "vache-vache", title: "Vache Vache (Telugu)", text: "Vache vache...", icon: "🐄", youtubeId: "FQ-lfN6WHG0", language: "Telugu" },
  { id: "pilla-pilla", title: "Pilla Pilla (Telugu)", text: "Pilla pilla...", icon: "👶", youtubeId: "2kUaylNjr4M", language: "Telugu" },
  { id: "tota-tota", title: "Tota Tota (Telugu)", text: "Tota tota...", icon: "🦜", youtubeId: "gAP4HPfvLqY", language: "Telugu" },
  { id: "poo-poo", title: "Poo Poo (Telugu)", text: "Poo poo railway...", icon: "🚂", youtubeId: "aQgLDVrPsk4", language: "Telugu" },
  { id: "janalu", title: "Janalu (Telugu)", text: "Janalu janalu...", icon: "🦴", youtubeId: "G6k7dChBaJ8", language: "Telugu" },
  { id: "chitti-papalu", title: "Chitti Papalu (Telugu)", text: "Chitti papalu...", icon: "🦋", youtubeId: "e_04ZrNroTo", language: "Telugu" },
  { id: "amma-ammamma", title: "Amma Ammamma (Telugu)", text: "Amma ammamma...", icon: "👵", youtubeId: "gAP4HPfvLqY", language: "Telugu" },
  { id: "chanda-chandamaama", title: "Chanda Chandamaama (Telugu)", text: "Chanda chandamaama...", icon: "🌙", youtubeId: "0F6WRYemPRE", language: "Telugu" },
  { id: "bus-bus", title: "Bus Bus (Telugu)", text: "Bus bus vastundi...", icon: "🚌", youtubeId: "e_04ZrNroTo", language: "Telugu" },
  { id: "chinna-chinna", title: "Chinna Chinna Pilla (Telugu)", text: "Chinna chinna pilla...", icon: "👧", youtubeId: "1dMG9sa8qUo", language: "Telugu" },
  { id: "pandu-pandu", title: "Pandu Pandu (Telugu)", text: "Pandu pandu...", icon: "🍎", youtubeId: "7Abj-_IecBw", language: "Telugu" },
  { id: "gummadi", title: "Gummadi Gummadi (Telugu)", text: "Gummadi gummadi...", icon: "🎃", youtubeId: "G1VW0NRHtMc", language: "Telugu" },
  { id: "chettu-chettu", title: "Chettu Chettu (Telugu)", text: "Chettu chettu...", icon: "🌳", youtubeId: "G6k7dChBaJ8", language: "Telugu" },
  { id: "neeru-neeru", title: "Neeru Neeru (Telugu)", text: "Neeru neeru...", icon: "💧", youtubeId: "Zu6o23Pu0Do", language: "Telugu" },
  { id: "sooryudu", title: "Sooryudu (Telugu)", text: "Sooryudu sooryudu...", icon: "☀️", youtubeId: "yCjJyiqpAuU", language: "Telugu" },
  { id: "pasupu-kumkuma", title: "Pasupu Kumkuma (Telugu)", text: "Pasupu kumkuma...", icon: "🎨", youtubeId: "DR-cfDsHCGA", language: "Telugu" },
  { id: "sankranthi", title: "Sankranthi Song (Telugu)", text: "Sankranthi panduga...", icon: "🪁", youtubeId: "G1VW0NRHtMc", language: "Telugu" },
  { id: "ugadi", title: "Ugadi Song (Telugu)", text: "Ugadi panduga...", icon: "🥭", youtubeId: "7Abj-_IecBw", language: "Telugu" },
  { id: "batukamma", title: "Batukamma (Telugu)", text: "Batukamma batukamma...", icon: "🌸", youtubeId: "V_Y0kppOXU4", language: "Telugu" },
  { id: "bonalu", title: "Bonalu Song (Telugu)", text: "Bonalu bonalu...", icon: "🪔", youtubeId: "V_Y0kppOXU4", language: "Telugu" },
  { id: "sirimalle", title: "Sirimalle Puvva (Telugu)", text: "Sirimalle puvva...", icon: "🌸", youtubeId: "V_Y0kppOXU4", language: "Telugu" },
  { id: "pilla-pilla-2", title: "Pilla Naduma (Telugu)", text: "Pilla naduma...", icon: "💃", youtubeId: "71hqRT9U0wg", language: "Telugu" },
  { id: "ammayi-ammayi", title: "Ammayi Ammayi (Telugu)", text: "Ammayi ammayi...", icon: "👩", youtubeId: "gAP4HPfvLqY", language: "Telugu" },
  { id: "nanne-nanne", title: "Nanne Nanne (Telugu)", text: "Nanne nanne...", icon: "👶", youtubeId: "2kUaylNjr4M", language: "Telugu" },

  // ============ TAMIL (30 rhymes) ============
  { id: "kanna-kanna", title: "Kanna Kanna (Tamil)", text: "Kanna kanna...", icon: "👦", youtubeId: "jkjkmOCkMqs", language: "Tamil" },
  { id: "nila-nila", title: "Nila Nila Odi Vaa (Tamil)", text: "Nila nila odi vaa...", icon: "🌙", youtubeId: "GtMuh3AgIwA", language: "Tamil" },
  { id: "chinna-chinna-tamil", title: "Chinna Chinna Aasai (Tamil)", text: "Chinna chinna...", icon: "💭", youtubeId: "1dMG9sa8qUo", language: "Tamil" },
  { id: "uyir-ezhuthukal", title: "Uyir Ezhuthukal (Tamil)", text: "A Aa E Ee...", icon: "🅰️", youtubeId: "EaRl0KZNEdQ", language: "Tamil" },
  { id: "appa-appa", title: "Appa Appa (Tamil)", text: "Appa appa amma amma...", icon: "👨‍👩‍👧", youtubeId: "G6k7dChBaJ8", language: "Tamil" },
  { id: "poove-poove", title: "Poove Poove (Tamil)", text: "Poove poove...", icon: "🌸", youtubeId: "V_Y0kppOXU4", language: "Tamil" },
  { id: "kuruvi-kuruvi", title: "Kuruvi Kuruvi (Tamil)", text: "Kuruvi kuruvi...", icon: "🐦", youtubeId: "1CwiL64PVlg", language: "Tamil" },
  { id: "aathi-aathi", title: "Aathi Aathi (Tamil)", text: "Aathi aathi...", icon: "🐘", youtubeId: "ubspZnidcak", language: "Tamil" },
  { id: "thanga-thangam", title: "Thanga Thangam (Tamil)", text: "Thanga thangam...", icon: "⭐", youtubeId: "yCjJyiqpAuU", language: "Tamil" },
  { id: "pasanga-pasanga", title: "Pasanga Pasanga (Tamil)", text: "Pasanga pasanga...", icon: "👦", youtubeId: "jkjkmOCkMqs", language: "Tamil" },
  { id: "amma-amma", title: "Amma Amma (Tamil)", text: "Amma amma...", icon: "👩", youtubeId: "gAP4HPfvLqY", language: "Tamil" },
  { id: "bus-tamil", title: "Bus Song (Tamil)", text: "Bus bus poidu...", icon: "🚌", youtubeId: "e_04ZrNroTo", language: "Tamil" },
  { id: "enn-enn", title: "Enn Enn (Tamil)", text: "Enn enn oru...", icon: "🔢", youtubeId: "DR-cfDsHCGA", language: "Tamil" },
  { id: "varna-varna", title: "Varna Varna (Tamil)", text: "Varna varna...", icon: "🌈", youtubeId: "DR-cfDsHCGA", language: "Tamil" },
  { id: "palam-palam", title: "Palam Palam (Tamil)", text: "Palam palam...", icon: "🍎", youtubeId: "7Abj-_IecBw", language: "Tamil" },
  { id: "paapa-paapa", title: "Paapa Paapa (Tamil)", text: "Paapa paapa...", icon: "👶", youtubeId: "2kUaylNjr4M", language: "Tamil" },
  { id: "meen-meen", title: "Meen Meen (Tamil)", text: "Meen meen...", icon: "🐟", youtubeId: "XqZsoesa55w", language: "Tamil" },
  { id: "naan-naan", title: "Naan Naan (Tamil)", text: "Naan naan...", icon: "👧", youtubeId: "1dMG9sa8qUo", language: "Tamil" },
  { id: "thaai-thaai", title: "Thaai Thaai (Tamil)", text: "Thaai thaai...", icon: "🇮🇳", youtubeId: "1CwiL64PVlg", language: "Tamil" },
  { id: "mazhai-mazhai", title: "Mazhai Mazhai (Tamil)", text: "Mazhai mazhai...", icon: "🌧️", youtubeId: "Zu6o23Pu0Do", language: "Tamil" },
  { id: "chandira-chandira", title: "Chandira Chandira (Tamil)", text: "Chandira chandira...", icon: "🌙", youtubeId: "GtMuh3AgIwA", language: "Tamil" },
  { id: "suryan-suryan", title: "Suryan Suryan (Tamil)", text: "Suryan suryan...", icon: "☀️", youtubeId: "yCjJyiqpAuU", language: "Tamil" },
  { id: "pattu-pattu", title: "Pattu Pattu (Tamil)", text: "Pattu pattu...", icon: "🐦", youtubeId: "1CwiL64PVlg", language: "Tamil" },
  { id: "kutty-kutty", title: "Kutty Kutty (Tamil)", text: "Kutty kutty...", icon: "👶", youtubeId: "jkjkmOCkMqs", language: "Tamil" },
  { id: "thanga-thangam-2", title: "Thanga Thangam (Tamil)", text: "Thanga thangam paattu...", icon: "⭐", youtubeId: "yCjJyiqpAuU", language: "Tamil" },
  { id: "pongal-pongal", title: "Pongal Pongal (Tamil)", text: "Pongal pongal...", icon: "🍚", youtubeId: "V_Y0kppOXU4", language: "Tamil" },
  { id: "diwali-tamil", title: "Diwali Song (Tamil)", text: "Diwali deepavali...", icon: "🪔", youtubeId: "V_Y0kppOXU4", language: "Tamil" },
  { id: "amma-amma-2", title: "Amma Vaa (Tamil)", text: "Amma vaa amma vaa...", icon: "👩", youtubeId: "gAP4HPfvLqY", language: "Tamil" },
  { id: "pattu-paattu", title: "Paattu Paattu (Tamil)", text: "Paattu paattu...", icon: "🎵", youtubeId: "71hqRT9U0wg", language: "Tamil" },
  { id: "naanum-rowdy", title: "Naanum Rowdy (Tamil)", text: "Naanum rowdy dhaan...", icon: "😊", youtubeId: "71hqRT9U0wg", language: "Tamil" },
  { id: "kollu-kollu", title: "Kollu Kollu (Tamil)", text: "Kollu kollu...", icon: "🐔", youtubeId: "gAP4HPfvLqY", language: "Tamil" },
  { id: "kaaka-kaaka", title: "Kaaka Kaaka (Tamil)", text: "Kaaka kaaka...", icon: "🐦", youtubeId: "1CwiL64PVlg", language: "Tamil" },

  // ============ KANNADA, MARATHI, GUJARATI (15 rhymes) ============
  { id: "beda-beda", title: "Beda Beda Magu (Kannada)", text: "Beda beda magu...", icon: "👶", youtubeId: "FUHy2rzxXaU", language: "Kannada" },
  { id: "chandoba", title: "Chandoba Chandoba (Marathi)", text: "Chandoba chandoba...", icon: "🌙", youtubeId: "nrmrkYUyCOQ", language: "Marathi" },
  { id: "sasa", title: "Sasa To Sasa (Marathi)", text: "Sasa to sasa...", icon: "🐰", youtubeId: "Bgwh5Gf35x8", language: "Marathi" },
  { id: "halarda", title: "Halarda (Gujarati)", text: "Halarda...", icon: "🎼", youtubeId: "Vz0FkXaGbPY", language: "Gujarati" },
  { id: "abc-gujarati", title: "ABC Song (Gujarati)", text: "A B C D...", icon: "🔤", youtubeId: "kR1p4-NPvfo", language: "Gujarati" },
  { id: "chhuk-chhuk", title: "Chhuk Chhuk Gadi (Gujarati)", text: "Chhuk chhuk gadi...", icon: "🚂", youtubeId: "aQgLDVrPsk4", language: "Gujarati" },
  { id: "gajanan", title: "Gajanan (Marathi)", text: "Gajanan gajanan...", icon: "🐘", youtubeId: "ubspZnidcak", language: "Marathi" },
  { id: "aaba", title: "Aaba (Kannada)", text: "Aaba aaba...", icon: "👶", youtubeId: "FUHy2rzxXaU", language: "Kannada" },
  { id: "barso-re", title: "Barso Re (Hindi/Marathi)", text: "Barso re barso re...", icon: "🌧️", youtubeId: "Zu6o23Pu0Do", language: "Marathi" },
  { id: "tota-tota-guj", title: "Tota Tota (Gujarati)", text: "Tota tota...", icon: "🦜", youtubeId: "gAP4HPfvLqY", language: "Gujarati" },
  { id: "haathi-gaj", title: "Haathi (Gujarati)", text: "Haathi haathi...", icon: "🐘", youtubeId: "ubspZnidcak", language: "Gujarati" },
  { id: "kannada-bus", title: "Bus Song (Kannada)", text: "Bus bus baruthe...", icon: "🚌", youtubeId: "e_04ZrNroTo", language: "Kannada" },
  { id: "marathi-abc", title: "ABC (Marathi)", text: "A B C D...", icon: "🔤", youtubeId: "75p-N9YKqNo", language: "Marathi" },
  { id: "kannada-gana", title: "Gana (Kannada)", text: "Ondu eradu mooru...", icon: "🔢", youtubeId: "DR-cfDsHCGA", language: "Kannada" },
  { id: "gujarati-rang", title: "Rang (Gujarati)", text: "Lal, peela, hara...", icon: "🌈", youtubeId: "DR-cfDsHCGA", language: "Gujarati" },
];

export const RHYME_COUNT = POPULAR_RHYMES.length;

/** Unique languages for filter dropdown (derived from data) */
export const RHYME_LANGUAGES = ["All", ...Array.from(new Set(POPULAR_RHYMES.map((r) => r.language).filter(Boolean))) as string[]];
